In [13]:
import copy

In [30]:
%run DataAnalysis.ipynb
mc = MonteCarlo(5, "isotropic")

In [31]:
mc.get_clusterdf()

,Cluster,Events,Channels,StartTime,TimeSpread,NRMSE,Zenith,Azimuth,ExtraCh,MissingCh,Fitline
0,0,7,7,8.607113e+05,0.0,1.099776,1.368808,-1.264106,0,0,"[227.345636, -2.730597, -225.767745, -0.295767..."
1,1,3,3,1.802328e+06,0.0,1.065271,1.224411,-1.395224,0,0,"[-286.937675, -347.56006, 155.453816, -0.16429..."
2,2,10,10,2.297936e+06,0.0,0.980175,0.995100,1.117864,0,0,"[281.326415, 274.633439, 321.888173, -0.367068..."
3,3,8,8,2.629062e+06,0.0,1.032985,1.162793,1.296488,0,0,"[48.460813, 152.848291, 28.103778, -0.248646, ..."

In [35]:
%run DataAnalysis.ipynb
da = DataAnalysis()
da.set_eventdf(mc.get_eventdf())
da.arrange_clusters()

In [36]:
da1 = copy.deepcopy(da)
da1.make_clusterdf(basicfit=True)
da1.get_clusterdf()

,Cluster,Events,Channels,StartTime,TimeSpread,NRMSE,Zenith,Azimuth,ExtraCh,MissingCh,Fitline
0,0,7,7,8.607113e+05,0.0,0.995887,1.304061,-1.271424,0,0,"[205.757143, 67.2, -240.285714, 0.284491, -0.9..."
1,1,3,3,1.802328e+06,0.0,0.594954,1.167186,1.570796,3,0,"[-323.7, -107.8, 251.333333, 0.0, -0.919649, -..."
2,2,10,10,2.297936e+06,0.0,0.935404,0.992223,1.074290,1,0,"[117.6, -58.8, 81.2, 0.398826, 0.736148, 0.54683]"
3,3,8,8,2.629062e+06,0.0,0.997115,1.146902,1.348582,1,0,"[0.0, -11.025, 101.5, 0.200884, 0.889082, -0.4..."

In [7]:
da2 = copy.deepcopy(da)
da2.make_clusterdf()
da2.get_clusterdf()

NSGA2 failure...defaulting to LSR
NSGA2 failure...defaulting to LSR
NSGA2 failure...defaulting to LSR

,Cluster,Events,Channels,StartTime,TimeSpread,NRMSE,Zenith,Azimuth,ExtraCh,MissingCh,Fitline
0,0,8,8,1.605207e+05,0.0,1.052999,1.045028,-1.422695,0,1,"[-40.65, -56.9625, 246.5, 0.127631, -0.85547, ..."
1,1,5,5,1.212675e+06,0.0,1.032681,0.911438,0.853407,0,0,"[198.743474, 108.170601, -226.872911, -260.039..."
2,2,9,9,1.273367e+06,0.0,0.751250,1.206893,0.247441,0,0,"[-19.633333, 93.1, 225.555556, 0.906051, 0.228..."
3,3,8,8,1.757446e+06,0.0,0.764046,0.504411,0.735279,3,1,"[165.375, 82.6875, -29.0, -0.35843, -0.324189,..."

In [8]:
da3 = copy.deepcopy(da)
da3.make_clusterdf(pop_num=50, gen_num=1000)
da3.get_clusterdf()

NSGA2 failure...defaulting to LSR

,Cluster,Events,Channels,StartTime,TimeSpread,NRMSE,Zenith,Azimuth,ExtraCh,MissingCh,Fitline
0,0,8,8,1.605207e+05,0.0,1.084753,1.054971,-1.383173,0,1,"[-64.079516, 67.466939, 176.861182, -50.033053..."
1,1,5,5,1.212675e+06,0.0,1.024375,0.904675,0.867122,0,0,"[195.135714, 107.554825, -223.579556, -277.379..."
2,2,9,9,1.273367e+06,0.0,0.751250,1.206893,0.247441,0,0,"[-19.633333, 93.1, 225.555556, 0.906051, 0.228..."
3,3,8,8,1.757446e+06,0.0,0.900497,0.520650,0.852182,1,0,"[256.844576, 186.960977, 210.23714, 81.025351,..."

In [11]:
da3 = copy.deepcopy(da)
da3.make_clusterdf(pop_num=50, gen_num=1500)
da3.get_clusterdf()

,Cluster,Events,Channels,StartTime,TimeSpread,NRMSE,Zenith,Azimuth,ExtraCh,MissingCh,Fitline
0,0,8,8,1.605207e+05,0.0,1.057105,1.038192,-1.418957,0,0,"[-58.922904, 49.82093, 182.298127, -39.536271,..."
1,1,5,5,1.212675e+06,0.0,1.038022,0.897154,0.878045,0,0,"[193.56595, 107.841615, -225.213762, -270.9732..."
2,2,9,9,1.273367e+06,0.0,0.758717,1.206919,0.259076,0,0,"[-135.184183, 61.652075, 179.316178, 298.90560..."
3,3,8,8,1.757446e+06,0.0,0.864790,0.510466,0.835199,1,0,"[256.844576, 184.494959, 209.676665, 80.649147..."