In [7]:
import numpy as np
import pandas as pd
import scipy as sc
import uproot as up

import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
events1 = up.open('WorkingDir/JulianUrop/ds3564/ds3564Tower1.root')['tree']
events2 = up.open('WorkingDir/JulianUrop/ds3564/ds3564Tower2.root')['tree']
events3 = up.open('WorkingDir/JulianUrop/ds3564/ds3564Tower3.root')['tree']

In [9]:
data1 = events1.pandas.df()
data2 = events2.pandas.df()
data3 = events3.pandas.df()

In [10]:
frames = [data1, data2, data3]
#concatenate the frames!
alldata = pd.concat(frames)

In [12]:
alldata

,Run,Channel,Time,NumPulses,OFdelay,MaxPosInWindow,SelectedEnergy,Baseline,MaxToBaseline,StabAmp
entry,,,,,,,,,,
0,350259,4,201.712,1,3.175603,3162,5350.867843,-2228.379725,2209.313868,6922.485707
1,350259,32,334.408,1,3.173095,3164,5333.960253,-4604.478149,3705.018311,7599.030650
2,350259,23,1922.776,1,3.209816,3208,4736.281316,-4649.411229,3223.717717,6487.084005
3,350259,6,3444.392,1,3.175244,3161,5341.670045,-4218.544189,3944.732849,7330.490097
4,350259,29,5731.368,1,3.168502,3158,5415.189283,-4729.856969,2827.517034,7222.235749
...,...,...,...,...,...,...,...,...,...,...
5492,350292,114,56794.440,1,3.167796,3157,5421.272356,-5553.591141,4017.427811,7289.098227
5493,350292,121,57099.312,1,3.157400,3151,5361.909907,-5679.889287,3389.663305,7204.117403
5494,350292,110,57219.152,1,3.143980,3136,5405.858305,-5484.677129,2970.707708,6880.517674
5495,350292,107,57425.824,1,3.150054,3146,5437.255739,-5890.038254,2908.715012,7246.557463
5496,350292,132,57820.512,1,3.170479,3162,5402.698545,-3933.762914,3999.692327,7360.432199